### ISSUE TITLE
Add Folders in Code

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#14]
**Is your feature request related to a problem? Please describe.**

Every time I try to find a document, I cannot find the correct one because the document title is always the same.

**Describe the solution you'd like**

Add folders.

**Comment by CodeAsherPlayz** [comment]
Thank you for finding this issue. We have finished looking into the issue. The rollout of the fix will be in v1.0. Thank you for stopping by our repository!

~CodeAsherPlayz

**Comment by CodeAsherPlayz** [comment]
We have looked into the issue but we would like to inform you that we will not be adding this in the next update or coming updates. This is because when coding, files must be in the same directory for this mechanism to work. There are 2 ways to link to another file. Absolute and Relative file. I can't do this because you may not be able to use the same file name as us. We will be rolling this update out in Version 3.0 but we will need some time as we have to modify many things.

**Comment by CodeAsherPlayz** [comment]
Update on #14

We have decided that we will add this feature in Version 3.0. However, you must look at the manual and comply with the manual for the update to work. If you do not comply with the manual, the software will break.
